SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
DROP SCHEMA if EXISTS `BOOK_STORE`;
CREATE SCHEMA `BOOK_STORE` DEFAULT CHARACTER SET latin1 ;
USE `BOOK_STORE` ;

-- -----------------------------------------------------
-- Table `BOOK_STORE`.`PUBLISHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOK_STORE`.`PUBLISHER` (
  `NAME` VARCHAR(45) NOT NULL,
  `ADDRESS` VARCHAR(90) NOT NULL,
  `TELEPHONE` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `BOOK_STORE`.`BOOK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOK_STORE`.`BOOK` (
  `ISBN` VARCHAR(15) NOT NULL,
  `TITLE` VARCHAR(90) NOT NULL,
  `SELLING_PRICE` FLOAT NOT NULL DEFAULT '0',
  `CATEGORY` VARCHAR(45) NOT NULL,
  `THRESHOLD` INT NOT NULL DEFAULT '1',
  `COPIES` INT NOT NULL DEFAULT '0',
  `PUBLISHER` VARCHAR(45) NOT NULL,
  `PUBLICATION_YEAR` DATE NULL DEFAULT NULL,
  `AUTHOR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `title_UNIQUE` (`TITLE` ASC),
  INDEX `PUBLISHER_idx` (`PUBLISHER` ASC),
  INDEX `CATEGORY_idx` (`CATEGORY` ASC),
  INDEX `AUTHOR_idx` (`AUTHOR` ASC),
  CONSTRAINT `fk_BOOK_PUBLISHER`
    FOREIGN KEY (`PUBLISHER`)
    REFERENCES `BOOK_STORE`.`PUBLISHER` (`NAME`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `BOOK_STORE`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOK_STORE`.`ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(15) NOT NULL,
  `QUANTITY` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`ORDER_ID`, `ISBN`),
  CONSTRAINT `fk_ORDER_ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `BOOK_STORE`.`BOOK` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `BOOK_STORE`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOK_STORE`.`USER` (
  `USER_NAME` VARCHAR(45) NOT NULL,
  `F_NAME` VARCHAR(45) NOT NULL,
  `L_NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(90) NOT NULL,
  `TELEPHONE` VARCHAR(15) NOT NULL,
  `ADDRESS` VARCHAR(90) NOT NULL,
  `PRIVILEGE` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_NAME`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `BOOK_STORE`.`SALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BOOK_STORE`.`SALES` (
  `SALES_ID` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(15) NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `DATE` DATE NOT NULL,
  `QUANTITY` INT NOT NULL,
  PRIMARY KEY (`SALES_ID`, `ISBN`, `USER_NAME`),
  INDEX `ISBN_idx` (`ISBN` ASC),
  INDEX `USER_NAME_idx` (`USER_NAME` ASC),
  CONSTRAINT `fk_SALES_ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `BOOK_STORE`.`BOOK` (`ISBN`)
    ON DELETE  CASCADE
    ON UPDATE  CASCADE,
  CONSTRAINT `fk_SALES_USER_NAME`
    FOREIGN KEY (`USER_NAME`)
    REFERENCES `BOOK_STORE`.`USER` (`USER_NAME`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `BOOK_STORE`;

-- -----------------------------------------------------
-- Triggers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Triggers for Table 'PUBLISHER'
-- -----------------------------------------------------
DELIMITER $$
USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_publisher_insert`
BEFORE INSERT ON `BOOK_STORE`.`PUBLISHER`
FOR EACH ROW
BEGIN 
	IF (NEW.NAME NOT REGEXP '^[a-zA-Z]{1,}$') THEN 
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID NAME';
	END IF;
	IF (NEW.ADDRESS NOT REGEXP '^[a-zA-Z0-9]{1,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID ADDRESS';
	END IF;
 	IF (NEW.TELEPHONE NOT REGEXP '^[0-9]{7,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID PHONE NUMBER';
	END IF;
END$$

USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_publisher_update`
BEFORE UPDATE ON `BOOK_STORE`.`PUBLISHER`
FOR EACH ROW
BEGIN 
	IF (NEW.NAME NOT REGEXP '^[a-zA-Z]{1,}$') THEN 
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID NAME';
	END IF;
	IF (NEW.ADDRESS NOT REGEXP '^[a-zA-Z0-9]{1,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID ADDRESS';
	END IF;
 	IF (NEW.TELEPHONE NOT REGEXP '^[0-9]{7,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID PHONE NUMBER';
	END IF;
END$$

-- -----------------------------------------------------
-- Triggers for Table 'BOOK'
-- -----------------------------------------------------
USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_book_insert`
BEFORE INSERT ON `BOOK_STORE`.`BOOK`
FOR EACH ROW
BEGIN
  IF NEW.ISBN NOT REGEXP '^[0-9]{1,}$' THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'INVALID ISBN';
  END IF;
  IF NEW.TITLE NOT REGEXP '^[a-zA-Z0-9]{1,}$' THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'INVALID TITLE';
  END IF;
  IF NEW.CATEGORY NOT IN ('science', 'art', 'religion', 'history', 'geography') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID CATEGORY';
  END IF;
  IF NEW.THRESHOLD < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE THRESHOLD';
  END IF;
  IF NEW.COPIES < NEW.THRESHOLD THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NUMBER OF COPIES LESS THAN THRESHOLD';
  END IF;
  IF NEW.SELLING_PRICE < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE SELLING PRICE';
  END IF;
END$$

USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_book_update`
BEFORE UPDATE ON `BOOK_STORE`.`BOOK`
FOR EACH ROW
BEGIN
  IF NEW.ISBN NOT REGEXP '^[0-9]{1,}$' THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'INVALID ISBN';
  END IF;
  IF NEW.TITLE NOT REGEXP '^[a-zA-Z0-9]{1,}$' THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'INVALID TITLE';
  END IF;
  IF NEW.CATEGORY NOT IN ('science', 'art', 'religion', 'history', 'geography') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID CATEGORY';
  END IF;
  IF NEW.THRESHOLD < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE THRESHOLD';
  END IF;
  -- 2. Modify existing books 
  IF NEW.COPIES < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE NUMBER OF COPIES';
  END IF;
  IF NEW.SELLING_PRICE < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE SELLING PRICE';
  END IF;
END$$

-- 3. Place orders on books
USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`after_book_update`
AFTER UPDATE ON `BOOK_STORE`.`BOOK`
FOR EACH ROW
BEGIN
  IF OLD.COPIES > NEW.COPIES AND NEW.COPIES < NEW.THRESHOLD THEN
    IF OLD.COPIES < OLD.THRESHOLD THEN
		INSERT INTO `ORDER` VALUES ( NEW.ISBN , OLD.THRESHOLD - NEW.COPIES ) ;
  	ELSE
  		INSERT INTO `ORDER` VALUES ( NEW.ISBN , OLD.COPIES - NEW.COPIES ) ;
  	END IF;
  END IF;
END$$

-- -----------------------------------------------------
-- Triggers for Table 'ORDER'
-- -----------------------------------------------------
USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_order_insert`
BEFORE INSERT ON `BOOK_STORE`.`ORDER`
FOR EACH ROW
BEGIN
  IF NEW.QUANTITY < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE NUMBER OF QUANTITY';
  END IF;
END$$

USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_order_update`
BEFORE UPDATE ON `BOOK_STORE`.`ORDER`
FOR EACH ROW
BEGIN
  IF NEW.QUANTITY < 0 THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT = 'NEGATIVE NUMBER OF QUANTITY';
  END IF;
END$$

-- 4. Confirm orders
USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_order_delete`
BEFORE DELETE ON `BOOK_STORE`.`ORDER`
FOR EACH ROW
BEGIN
  UPDATE `BOOK` SET COPIES = COPIES + OLD.QUANTITY WHERE BOOK.ISBN = OLD.ISBN;
END$$

-- -----------------------------------------------------
-- Triggers for Table 'USER'
-- -----------------------------------------------------
USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_user_insert`
BEFORE INSERT ON `BOOK_STORE`.`USER`
FOR EACH ROW
BEGIN 
 	IF (NEW.USER_NAME NOT REGEXP '[a-zA-Z0-9]{1,}$') THEN 
 		SIGNAL SQLSTATE '45000' 
 		SET MESSAGE_TEXT = 'INVALID USER_NAME';
 	END IF;
 	IF (NEW.F_NAME NOT REGEXP '^[a-zA-Z]{1,}$') THEN 
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID FIRST_NAME';
	END IF;
 	IF (NEW.L_NAME NOT REGEXP '^[a-zA-Z]{1,}$}') THEN 
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID LAST_NAME';
	END IF;
 	IF (NEW.EMAIL NOT REGEXP '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$') THEN
 		SIGNAL SQLSTATE '45000' 
 		SET MESSAGE_TEXT = 'INVALID EMAIL';
 	END IF;
	IF (NEW.PASSWORD NOT REGEXP '^.*[0-9]') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'PASSWORD MUST INCLUDE AT LEAST ONE DIGIT';
	END IF;
	IF (NEW.PASSWORD NOT REGEXP '^[a-zA-Z0-9]{7,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'PASSWORD HAS NO SPECIAL CHARS AND AT LEAST 8 CHARS';
	END IF;
	IF (NEW.TELEPHONE NOT REGEXP '^[0-9]{7,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID PHONE NUMBER';
	END IF;
	IF (NEW.ADDRESS NOT REGEXP '^[a-zA-Z0-9]{1,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID ADDRESS';
	END IF;
END$$

USE `BOOK_STORE`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `BOOK_STORE`.`before_user_update`
BEFORE UPDATE ON `BOOK_STORE`.`USER`
FOR EACH ROW
BEGIN 
 	IF (NEW.USER_NAME NOT REGEXP '[a-zA-Z0-9]{1,}$') THEN 
 		SIGNAL SQLSTATE '45000' 
 		SET MESSAGE_TEXT = 'INVALID USER_NAME';
 	END IF;
 	IF (NEW.F_NAME NOT REGEXP '^[a-zA-Z]{1,}$') THEN 
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID FIRST_NAME';
	END IF;
 	IF (NEW.L_NAME NOT REGEXP '^[a-zA-Z]{1,}$}') THEN 
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID LAST_NAME';
	END IF;
 	IF (NEW.EMAIL NOT REGEXP '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$') THEN
 		SIGNAL SQLSTATE '45000' 
 		SET MESSAGE_TEXT = 'INVALID EMAIL';
 	END IF;
	IF (NEW.PASSWORD NOT REGEXP '^.*[0-9]') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'PASSWORD MUST INCLUDE AT LEAST ONE DIGIT';
	END IF;
	IF (NEW.PASSWORD NOT REGEXP '^[a-zA-Z0-9]{7,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'PASSWORD HAS NO SPECIAL CHARS AND AT LEAST 8 CHARS';
	END IF;
	IF (NEW.TELEPHONE NOT REGEXP '^[0-9]{7,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID PHONE NUMBER';
	END IF;
	IF (NEW.ADDRESS NOT REGEXP '^[a-zA-Z0-9]{1,}$') THEN
		SIGNAL SQLSTATE '45000' 
		SET MESSAGE_TEXT = 'INVALID ADDRESS';
	END IF;
END$$

DELIMITER ;